#!/usr/bin/env node
/**
 * Generates `src/generated/version.ts` from `package.json`.
 *
 * This script runs at build time, never at CLI runtime, to avoid reading
 * `package.json` from disk every time `snaprun` starts.
 *
 * The npm package name and CLI binary name are intentionally distinct:
 * - npm package: @timoogo/snaprun
 * - CLI command: snaprun
 */
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(
  readFileSync(join(rootDir, "package.json"), "utf-8"),
);

const binaryNames = Object.keys(pkg.bin ?? {});

if (binaryNames.length !== 1) {
  throw new Error(
    `Expected exactly one CLI binary in package.json, found ${binaryNames.length}.`,
  );
}

const cliName = binaryNames[0];

const outDir = join(rootDir, "src", "generated");
const outFile = join(outDir, "version.ts");

const content = `// This file is automatically generated by scripts/generate-version.mjs.
// Do not edit manually: it is regenerated from package.json.

export const CLI_NAME = ${JSON.stringify(cliName)};
export const CLI_VERSION = ${JSON.stringify(pkg.version)};
export const CLI_DESCRIPTION = ${JSON.stringify(pkg.description)};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, content);